# Get the latest version of Playwright
FROM mcr.microsoft.com/playwright:focal AS playwright

# Install necessary dependencies for Chrome and ffmpeg
RUN apt-get update && apt-get install -y wget gnupg libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev



# Set the work directory for the application
WORKDIR /app

# Set the environment path to node_modules/.bin
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json to the app folder in Docker image
COPY package.json package-lock.json /app/

# Install the dependencies in Node environment
RUN npm ci --only=production

# Copy the installed dependencies from playwright image to base image
COPY --from=playwright /usr/local/share/. /usr/local/share/

# Copy the installed dependencies from playwright image to base image
COPY --from=playwright /usr/local/lib/node_modules/ /usr/local/lib/node_modules/

# Set the environment variable for ffmpeg
ENV FFMPEG_PATH /usr/local/share/ffmpeg

# Copy the necessary files to the app folder in Docker image
COPY . /app

# Expose port
EXPOSE 8080
EXPOSE 8081
EXPOSE 4000

# Run the app
CMD [ "node", "start.js" ]


